"""Shared runtime models for app-first execution."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class RunMode(str, Enum):
    """Execution authority mode."""

    SUPERVISED = "supervised"
    AUTOPILOT = "autopilot"
    MANUAL = "manual"


class RunStatus(str, Enum):
    """Top-level run lifecycle state."""

    RUNNING = "running"
    PENDING_APPROVAL = "pending_approval"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class StepStatus(str, Enum):
    """Step lifecycle state."""

    PENDING = "pending"
    RUNNING = "running"
    PENDING_APPROVAL = "pending_approval"
    COMPLETED = "completed"
    REJECTED = "rejected"
    FAILED = "failed"


class ApprovalDecision(str, Enum):
    """Approval decision on a high-risk step."""

    APPROVE = "approve"
    REJECT = "reject"


class RiskTier(str, Enum):
    """Risk tier used by policy gates."""

    LOW = "low"
    HIGH = "high"


class StepDefinition(BaseModel):
    """User or planner provided execution step."""

    action_type: str = Field(min_length=1, max_length=64)
    instruction: str = Field(min_length=1, max_length=2000)


class DelegationStepPayload(BaseModel):
    """Structured payload for bounded delegation steps."""

    role: str = Field(min_length=1, max_length=64)
    objective: str = Field(min_length=1, max_length=2000)
    mode: RunMode = RunMode.MANUAL
    summary: str = Field(default="", max_length=4000)
    steps: list[StepDefinition] = Field(default_factory=list)


class CitationRecord(BaseModel):
    """Citation generated by execution."""

    url: str
    title: str
    snippet: str


class ArtifactRecord(BaseModel):
    """Artifact generated by execution."""

    kind: str = "text"
    name: str
    rel_path: str
    sandbox_path: str
    sha256: str


class StepExecutionResult(BaseModel):
    """Result returned by the execution adapter for one step."""

    output_text: str = ""
    citations: list[CitationRecord] = Field(default_factory=list)
    artifacts: list[ArtifactRecord] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class RunEvent(BaseModel):
    """Event emitted to timeline stream subscribers."""

    run_id: str
    event_type: str
    payload: dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
