"""App-first bootstrap helpers for first-run setup."""

from __future__ import annotations

import os
import secrets
from threading import Timer

from dotenv import dotenv_values

from nexus_api.config import ApiSettings
from nexus_api.schemas import (
    BootstrapConfigureRequest,
    BootstrapConfigureResponse,
    BootstrapStatusResponse,
)

DEFAULT_ADMIN_PASSWORD = "change-me-now"
DEFAULT_APP_DATABASE_URL = "postgresql+psycopg://nexus:nexus@nexus-postgres:5432/nexus"
DEFAULT_DOCKER_STEP_IMAGE = "agent-nexus-sandbox-step:local"


def bootstrap_status(settings: ApiSettings) -> BootstrapStatusResponse:
    config_path = settings.config_path
    env_values = _load_env_values(config_path)
    password = (
        env_values.get("APP_ADMIN_PASSWORD")
        or settings.APP_ADMIN_PASSWORD
        or DEFAULT_ADMIN_PASSWORD
    )
    uses_default = password == DEFAULT_ADMIN_PASSWORD
    configured = bool(env_values) and not uses_default
    if not configured and settings.APP_ADMIN_PASSWORD != DEFAULT_ADMIN_PASSWORD:
        configured = True
        uses_default = False
    return BootstrapStatusResponse(
        setup_required=not configured,
        configured=configured,
        config_path=str(config_path),
        uses_default_admin_password=uses_default,
    )


def write_bootstrap_config(
    settings: ApiSettings,
    request: BootstrapConfigureRequest,
) -> BootstrapConfigureResponse:
    status = bootstrap_status(settings)
    if not status.setup_required:
        raise ValueError("App is already configured")

    config_path = settings.config_path
    env_values = _load_env_values(config_path)
    env_values["APP_DATABASE_URL"] = env_values.get("APP_DATABASE_URL", DEFAULT_APP_DATABASE_URL)
    env_values["APP_ADMIN_USERNAME"] = request.admin_username.strip()
    env_values["APP_ADMIN_PASSWORD"] = request.admin_password
    env_values["APP_CANONICAL_WORKSPACE"] = env_values.get(
        "APP_CANONICAL_WORKSPACE",
        settings.APP_CANONICAL_WORKSPACE,
    )
    env_values["APP_SANDBOX_ARTIFACT_ROOT"] = env_values.get(
        "APP_SANDBOX_ARTIFACT_ROOT",
        settings.APP_SANDBOX_ARTIFACT_ROOT,
    )
    env_values["SANDBOX_RUNNER_TOKEN"] = env_values.get(
        "SANDBOX_RUNNER_TOKEN",
        settings.SANDBOX_RUNNER_TOKEN or secrets.token_urlsafe(24),
    )
    env_values["SANDBOX_EXECUTION_BACKEND"] = request.sandbox_backend
    env_values["SANDBOX_BROWSER_MODE"] = request.browser_mode
    env_values["SANDBOX_CAPTURE_SCREENSHOT"] = env_values.get(
        "SANDBOX_CAPTURE_SCREENSHOT",
        "1",
    )

    if request.sandbox_backend in {"docker", "docker-host"}:
        env_values["SANDBOX_DOCKER_IMAGE"] = DEFAULT_DOCKER_STEP_IMAGE
        env_values["SANDBOX_DOCKER_ALLOWED_IMAGES"] = DEFAULT_DOCKER_STEP_IMAGE
        env_values["SANDBOX_DOCKER_ALLOW_UNPINNED_LOCAL"] = "1"
        if request.sandbox_backend == "docker":
            env_values["SANDBOX_DOCKER_HOST"] = "tcp://nexus-sandbox-dind:2376"
            env_values["SANDBOX_DOCKER_TLS_VERIFY"] = "1"
            env_values["SANDBOX_DOCKER_CERT_PATH"] = "/certs/client"
        else:
            env_values["SANDBOX_DOCKER_HOST"] = "unix:///var/run/docker.sock"
            env_values["SANDBOX_DOCKER_TLS_VERIFY"] = "0"
            env_values["SANDBOX_DOCKER_CERT_PATH"] = ""

    if request.openrouter_api_key.strip():
        env_values["OPENROUTER_API_KEY"] = request.openrouter_api_key.strip()
    if request.discord_token.strip():
        env_values["DISCORD_TOKEN"] = request.discord_token.strip()
        env_values["DISCORD_BRIDGE_CHANNEL"] = request.discord_bridge_channel.strip() or "human"
    if request.public_host.strip():
        env_values["NEXUS_PUBLIC_HOST"] = request.public_host.strip()
    if request.acme_email.strip():
        env_values["ACME_EMAIL"] = request.acme_email.strip()

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_render_env_file(env_values), encoding="utf-8")

    if settings.APP_BOOTSTRAP_EXIT_AFTER_CONFIGURE:
        _schedule_exit()

    return BootstrapConfigureResponse(
        configured=True,
        restart_required=True,
        config_path=str(config_path),
    )


def _load_env_values(path) -> dict[str, str]:
    if not path.exists():
        return {}
    return {key: value for key, value in dotenv_values(path).items() if key and value is not None}


def _render_env_file(values: dict[str, str]) -> str:
    lines = [
        "# Generated by Agent Nexus app-first bootstrap",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={_quote_env_value(str(values[key]))}")
    lines.append("")
    return "\n".join(lines)


def _quote_env_value(value: str) -> str:
    if value == "":
        return '""'
    if any(ch.isspace() for ch in value) or any(ch in value for ch in '#"'):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _schedule_exit() -> None:
    timer = Timer(0.25, _exit_process)
    timer.daemon = True
    timer.start()


def _exit_process() -> None:
    os._exit(0)
